# Piotriski Strategy Data Mining

### Get Data

In [1]:
import requests 
import pandas as pd
from bs4 import BeautifulSoup 
import json
def get_data(URL):
    stockFinancialData = []
    try:
        r = requests.get(URL) 
        soup = BeautifulSoup(r.content, 'html5lib') 
        script = soup.find('script', attrs = {'id':'__NEXT_DATA__'})  
        line_str = str(script)
        first_line = '<script id="__NEXT_DATA__" type="application/json">'
        second_line = "</script>"
        idx1 = line_str.find(first_line)
        idx2 = line_str.find(second_line)
        result = line_str[idx1 + len(first_line): idx2]
        json_object = json.loads(result)
        stockFinancialData = json_object['props']['pageProps']["stockFinancialData"]
        return stockFinancialData
    except Exception as e:
        print(e)
        return stockFinancialData

### Data Structuring

In [2]:
def data_structuring(stockFinancialData):
    annualCashFlow = {}
    annualBalance = {}
    annualIncome = {}
    quarterlyCashFlow = {}
    quarterlyBalance = {}
    quarterlyIncome = {}
    for i in range(0,len(stockFinancialData)):
        #Checking if the report is Annual or not
        if stockFinancialData[i]["Type"] == "Annual":
            fiscalYear = stockFinancialData[i]["FiscalYear"]
            annualCashFlow[fiscalYear] = {}
            annualBalance[fiscalYear] = {}
            annualIncome[fiscalYear] = {}
            try:
                cashFlow = stockFinancialData[i]["stockFinancialMap"]["CAS"]
                balanceSheet = stockFinancialData[i]["stockFinancialMap"]["BAL"]
                incomeStatement = stockFinancialData[i]["stockFinancialMap"]["INC"]
                for cash in cashFlow:
                    annualCashFlow[fiscalYear][cash["key"]] = cash["value"]
                for balance in balanceSheet:
                    annualBalance[fiscalYear][balance["key"]] = balance["value"]
                for income in incomeStatement:
                    annualIncome[fiscalYear][income["key"]] = income["value"]
            except Exception as e:
                print("Skipping this year for stock",e)
        else:
            endDate = stockFinancialData[i]["EndDate"]
            quarterlyCashFlow[endDate] = {}
            quarterlyBalance[endDate] = {}
            quarterlyIncome[endDate] = {}
            # incomeStatement = []
            try:
                incomeStatement = stockFinancialData[i]["stockFinancialMap"]["INC"]
                cashFlow = stockFinancialData[i]["stockFinancialMap"]["CAS"]
                balanceSheet = stockFinancialData[i]["stockFinancialMap"]["BAL"]
                for cash in cashFlow:
                    quarterlyCashFlow[endDate][cash["key"]] = cash["value"]
                for balance in balanceSheet:
                    quarterlyBalance[endDate][balance["key"]] = balance["value"]
                for income in incomeStatement:
                    quarterlyIncome[endDate][income["key"]] = income["value"]
            except Exception as e:
                # print("Cashflow and balance not found for {}".format(endDate))
                for income in incomeStatement:
                    quarterlyIncome[endDate][income["key"]] = income["value"]
    return annualCashFlow,annualBalance,annualIncome,quarterlyCashFlow,quarterlyBalance,quarterlyIncome

In [3]:
characters_to_replace = ['/', '(', ')', '-']
def change_column_names(s, chars, replacement='_'):
    for char in chars:
        s = s.replace(char, replacement)
    return s

### Generate DataFrames

In [4]:
from sqlalchemy import create_engine,inspect
user = 'akshayparate'
passw = 'akshayparate'
host =  '182.48.201.235'
port = 3306
database = 'stock_fundamentals'
# Create an engine instance
engine = create_engine(f'mysql+pymysql://{user}:{passw}@{host}:{port}/{database}')

def generate_dataframes(annual,quarterly,stockName):
    annualdf = pd.DataFrame(annual).transpose()
    annualdf["Annual/Quarter"] = "Annual"
    quarter_df = pd.DataFrame(quarterly).transpose()
    quarter_df["Annual/Quarter"] = "Quarter"
    finalDf = pd.concat([annualdf, quarter_df], axis=0)
    finalDf["stockName"] = stockName
    finalDf = finalDf.reset_index()
    modified_columns_names = [change_column_names(s, characters_to_replace) for s in list(finalDf.columns)]
    finalDf.columns = modified_columns_names
    finalDf = finalDf.rename(columns={'index': 'Year_Date'})
    return finalDf

### Preventing Duplication

In [5]:
def check_if_data_already_exists_in_dataframe(existing_df,new_df,tableName):
    dataframes = [existing_df,new_df]
    all_columns = list(set().union(*(df.columns for df in dataframes)))
    # Ensure all DataFrames have the same columns
    for i, df in enumerate(dataframes):
        for col in all_columns:
            if col not in df.columns:
                df[col] = pd.NA
        dataframes[i] = df[all_columns]
    # Concatenate all DataFrames
    combined_df = pd.concat(dataframes, ignore_index=True)
    unique_stocks = combined_df['stockName'].unique()
    df_unique = pd.DataFrame()
    for u in unique_stocks:
        temp_df = combined_df[combined_df["stockName"]== u]
        temp_df = temp_df.drop_duplicates(subset=['Year_Date'])
        df_unique = pd.concat([df_unique,temp_df], ignore_index=True)
    return df_unique

### Merge DataFrames

In [6]:
def merge_dataframes(dataframes,existing_df,tableName,flag):
    all_columns = list(set().union(*(df.columns for df in dataframes)))
    # Ensure all DataFrames have the same columns
    for i, df in enumerate(dataframes):
        for col in all_columns:
            if col not in df.columns:
                df[col] = pd.NA
        dataframes[i] = df[all_columns]
    
    # Concatenate all DataFrames
    combined_df = pd.concat(dataframes, ignore_index=True)
    if flag:
        combined_df = check_if_data_already_exists_in_dataframe(existing_df,combined_df,tableName)
    return combined_df

### Store Data

In [7]:
def get_tables_from_database():
    inspector = inspect(engine)
    tables = inspector.get_table_names()
    return tables

In [8]:
def store_data(df,tableName,flag):
    if flag:
        df.to_sql(tableName, con=engine, if_exists='replace', index=False)
    else:
        df.to_sql(tableName, con=engine, if_exists='replace', index=False)

### Collect Data

In [9]:
livemintDetails = pd.read_csv("LiveMint.csv")[["stockLink","stockName"]]
stockLinks = list(livemintDetails["stockLink"])
stockNames = list(livemintDetails["stockName"])

db_tables = get_tables_from_database()
flag = False

df_dict = {"cashFlowDf":[],"balanceSheetDf":[],"incomeSheetDf":[]}
for i in range(0,1863):
    print(i,stockNames[i])
    try:
        stockFinancialData = get_data(stockLinks[i])
        annualCashFlow,annualBalance,annualIncome,quarterlyCashFlow,quarterlyBalance,quarterlyIncome = data_structuring(stockFinancialData)
        cashFlowDf = generate_dataframes(annualCashFlow,quarterlyCashFlow,stockNames[i])
        balanceSheetDf = generate_dataframes(annualBalance,quarterlyBalance,stockNames[i])
        incomeSheetDf = generate_dataframes(annualIncome,quarterlyIncome,stockNames[i])
        df_dict["cashFlowDf"].append(cashFlowDf)
        df_dict["balanceSheetDf"].append(balanceSheetDf)
        df_dict["incomeSheetDf"].append(incomeSheetDf)
    except Exception as e:
        print(e)

if len(db_tables) != 0:
    flag = True
    existing_cashFlowDf = pd.read_sql('SELECT * FROM {}'.format("cashflow"), con=engine)
    existing_balanceSheetDf = pd.read_sql('SELECT * FROM {}'.format("balancesheet"), con=engine)
    existing_incomeSheetDf = pd.read_sql('SELECT * FROM {}'.format("incomesheet"), con=engine)
    cashFlowDf = merge_dataframes(df_dict["cashFlowDf"],existing_cashFlowDf,"cashflow",True)
    balanceSheetDf = merge_dataframes(df_dict["balanceSheetDf"],existing_balanceSheetDf,"balancesheet",True)
    incomeSheetDf = merge_dataframes(df_dict["incomeSheetDf"],existing_incomeSheetDf,"incomesheet",True)
else:
    flag = False
    cashFlowDf = merge_dataframes(df_dict["cashFlowDf"],[],"cashflow",False)
    balanceSheetDf = merge_dataframes(df_dict["balanceSheetDf"],[],"balancesheet",False)
    incomeSheetDf = merge_dataframes(df_dict["incomeSheetDf"],[],"incomesheet",False)

store_data(cashFlowDf,"cashflow",flag)
store_data(balanceSheetDf,"balancesheet",flag)
store_data(incomeSheetDf,"incomesheet",flag)

1500 Tijaria Polypipes
1501 Gujarat Lease Financing
1502 Integra Essentia
1503 Sands Power Switchgears
1504 Euro Ceramics
1505 Mic Electronics
1506 GACM Technologies
1507 Consolidated Construction Consortium
1508 Nu Tek India
Skipping this year for stock 'CAS'
1509 Hb Stockholdings
1510 Jumbo Bag
1511 Parenteral Drugs India
1512 Easun Reyrolle
1513 KSK Energy Ventures
1514 Premier
1515 Ortel Communications
1516 Impex Ferro Tech
1517 GB Global
1518 Orchid Pharma
1519 Ramgopal Polytex
object of type 'NoneType' has no len()
1520 Univa Foods
1521 Infomedia Press
1522 Diamond Power Infrastructure
1523 Salona Cotspin
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
1524 Visagar Polytex
1525 Shah Metacorp
1526 Rajdarshan Industries
1527 Next Mediaworks
1528 Nagreeka Capital &amp; Infra
1529 Landmark Property Development
1530 Creative Eye
1531 Ashapura Intimates Fashion
1532 Lakshmi Precision Screws
object of type 'NoneType' has no len()
1533 Eurotex Industries &amp; Exports
1534 Dolphin Offshore Enterprises India
1535 Cyber Media India
1536 Barak Valley Cements
1537 Nk Industries
1538 Sathavahana Ispat
1539 Blue Coast Hotels
1540 Winsome Yarns
1541 Adroit Infotech
1542 Icsa India
1543 Diligent Media Corporation
1544 MVL
Skipping this year for stock 'CAS'
1545 Teamo Productions HQ
1546 Onelife Capital Advisors
1547 Rainbow Paper
1548 Gujarat Raffia Industries
1549 Techindia Nirman
1550 Blue Blends India
1551 Grand Foundry
1552 Regency Ceramics
1553 Shyam Telecom
1554 DCM Financial Services
1555 Blue Chip India
object of type 'NoneType' has no len()
1556 Kanani Industries
1557 Tantia Construction
1558 Celestial Biolabs
Skipping this year for stock 'CAS'
1559 Metkore Alloys &amp; Industries
1560 Tarapur Transformers
1561 Bharatiya Global Infomedia
1562 Apoorva Leasing Finance &amp; Investment Company
object of type 'NoneType' has no len()
1563 Medico Intercontinental
1564 Aban Offshore PRF
object of type 'NoneType' has no len()
1565 Capfin India
1566 Decillion Finance
object of type 'NoneType' has no len()
1567 Dalmia Industrial Development
1568 Unifinz Capital India
object of type 'NoneType' has no len()
1569 Aban Offshore PRF
1570 Infrastructure Leasing &amp; Financial Services PRF
object of type 'NoneType' has no len()
1571 Infrastructure Leasing &amp; Financial Services PRF
object of type 'NoneType' has no len()
1572 Infrastructure Leasing &amp; Financial Services PRF
object of type 'NoneType' has no len()
1573 Infrastructure Leasing &amp; Financial Services PRF
object of type 'NoneType' has no len()
1574 Infrastructure Leasing &amp; Financial Services PRF
object of type 'NoneType' has no len()
1575 Smart Finsec
1576 Sharanam Infrapro &amp; Trading
object of type 'NoneType' has no len()
1577 Premier Synthetics PRF
1578 Rotographics (India)
object of type 'NoneType' has no len()
1579 Valiant Organics PRF
1580 Gitanjali Gems
1581 Bharati Defence &amp; Infrastructure
1582 Pratibha Industries
1583 Jain Studios
Skipping this year for stock 'CAS'
1584 Pincon Spirit
1585 Lakshmi Energy &amp; Foods
1586 JIK Industries
1587 Ambica Agarbathies &amp; Aroma
Skipping this year for stock 'BAL'
1588 Equippp Social Impact Technologies
1589 Gangotri Textiles
1590 Visu International
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
1591 Indinfravit Trust
1592 K Lifestyle &amp; Industries
1593 Amit Spinning Industries
1594 DS Kulkarni Developers
Skipping this year for stock 'CAS'
1595 Quintegra Solutions
1596 Valecha Engineering
1597 Visesh Infotecnics
1598 POPEES CARES
1599 Rajasthan Petro Synthetics
object of type 'NoneType' has no len()
1600 Modern Threads India
1601 Rajvir Industries
1602 Abhishek Corparation
1603 Tulsi Extrusions
Skipping this year for stock 'CAS'
1604 ATN International
object of type 'NoneType' has no len()
1605 Atcom Technologies
object of type 'NoneType' has no len()
1606 ICDS
1607 Kavveri Telecom Products
1608 DSJ Keep Learning
1609 Nakoda
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
1610 Paras Petrofils
1611 Fedders Electric &amp; Engineering
1612 Tulsyan Nec
1613 Cairn India
1614 Sab Events &amp; Governance Now Media
object of type 'NoneType' has no len()
1615 Duncans Industries
object of type 'NoneType' has no len()
1616 Resurgere Mines &amp; Minerals India
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
1617 Gujarat NRE Coke DVR
Skipping this year for stock 'CAS'
1618 Tamilnadu Telecommunications
1619 Tecil Chemicals &amp; Hydro Power
1620 SBI Home Finance
object of type 'NoneType' has no len()
1621 RESTAURANT BR
1622 Jindal Cotex
1623 Prudential Sugar Corporation
1624 Value Industries
1625 Norben Tea &amp; Exports
object of type 'NoneType' has no len()
1626 LCC Infotech
1627 Khaitan India
1628 Bodhi Tree Multimedia
1629 Sigma Solve
1630 TARC
Skipping this year for stock 'CAS'
1631 Ravinder Heights
1632 Central Depository Service India
1633 BSE
1634 Sundaram Finance Holdings
1635 Marine Electricals (India)
1636 Vertoz Advertising
Skipping this year for stock 'CAS'
1637 Shrenik
1638 Dangee Dums
1639 Hi-Tech Pipes
1640 Sirca Paints India
1641 Madhav Copper
1642 Sanginita Chemicals
1643 Ice Make Refrigeration
1644 Sakar Healthcare
1645 Creative Newtech
1646 Shradha Infraprojects
1647 Global Education
1648 Akash Infra Projects
1649 Wealth First Portfolio Managers
1650 Suumaya Industries
1651 Infobean Technologies
1652 Zota Health Care
1653 Globe Textiles (India)
1654 Tembo Global
1655 Banka Bioloo
1656 Kothari Sugars &amp; Chemicals
1657 Silgo Retail
1658 JOCIL
1659 Agro Phos India
1660 Rudrabhishek Enterprises
1661 Pansari Developers
1662 Libas Consumer Products
1663 Aakash Exploration Services
1664 Worth Peripherals
1665 Vardhman Acrylics
1666 Elgi Rubber Company
1667 Vaishali Pharma
1668 Uravi T &amp; Wedge Lamps
1669 Shiv Aum Steels
object of type 'NoneType' has no len()
1670 Jash Engineering
1671 Pashupati Cotspin
object of type 'NoneType' has no len()
1672 R M Drip &amp; Sprinklers Systems
object of type 'NoneType' has no len()
1673 Panache Digilife
1674 B&amp;B Triplewall Containers
1675 D P Wires
Skipping this year for stock 'CAS'
1676 Ganga Forging
Skipping this year for stock 'CAS'
1677 Kothari Petrochemicals
1678 South West Pinnacle Exploration
1679 Giriraj Civil Developers
1680 Mmp Industries
1681 GKW
1682 Steel City Securities
1683 Apollo Sindoori Hotels
1684 ASL Industries
1685 Rkec Projects
1686 Iris Clothings
1687 N B I Industrial Finance Company
1688 Sanco Industries
1689 Balaxi Pharmaceuticals
1690 Total Transport Systems
Skipping this year for stock 'CAS'
1691 Sagardeep Alloys
1692 Mittal Life Style
1693 Maheshwari Logistics
1694 Thejo Engineering
1695 Consolidated Finvest &amp; Hold
1696 Rajshree Polypack
1697 M K Proteins
1698 Aarvi Encon
1699 Jullundur Motor Agency (Delhi)
1700 Marshall Machines
1701 Priti International
1702 Macpower Cnc Machines
1703 DPSC
1704 Geekay Wires
1705 Kshitij Polyline
1706 AKG Exim
1707 SONAM
1708 Airan
1709 Arvee Laboratories India
1710 Prolife Industries
1711 Softtech Engineers
1712 Shriram Pistons &amp; Rings
1713 Sintercom India
Skipping this year for stock 'BAL'
1714 Silver Touch Technologies
1715 Aspinwall &amp; Company
1716 Vinny Overseas
1717 Aaron Industries
1718 Dev Information Technology
1719 Spectrum Electrical Industries
1720 Shanti Overseas (India)
1721 Mahickra Chemicals
1722 Avro India
1723 Par Drugs &amp; Chemicals
1724 Vaxtex Cotfab
object of type 'NoneType' has no len()
1725 Ajooni Biotech
1726 Sumit Woods
1727 Kritika Wires
object of type 'NoneType' has no len()
1728 Beta Drugs
1729 Nitiraj Engineers
1730 Godha Cabcon &amp; Insulation
1731 Accuracy Shipping
Skipping this year for stock 'CAS'
1732 Artedz Fabs
object of type 'NoneType' has no len()
1733 Reliable Data Services
1734 Ahlada Engineers
1735 United Nilgiri Tea Estates Co
1736 G-Tec Jainx Education
1737 Hindcon Chemicals
1738 AAA Technologies
1739 SUPREME ENGIN
1740 KHFM Hospitality &amp; Facility
1741 E2E Networks
1742 Rajnandini Metal
1743 AVSL Industries
1744 Uniinfo Telecom Services
1745 Laxmi Goldorna House
1746 3rd Rock Multimedia
object of type 'NoneType' has no len()
1747 ShreeOswal Seeds &amp; Chemicals
object of type 'NoneType' has no len()
1748 Shri Ram Switchgears
object of type 'NoneType' has no len()
1749 Precot
1750 Salasar Exteriors &amp; Contour
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
1751 Ace Integrated Solutions
1752 DEBOCK INDUST
1753 Art Nirman
1754 D P ABHUSHAN ORD
1755 Goldstar Power
1756 Gretex Industries
object of type 'NoneType' has no len()
1757 Ksolves India
1758 Osia Hyper Retail
object of type 'NoneType' has no len()
1759 A&amp;M Jumbo Bags
object of type 'NoneType' has no len()
1760 Shree Ram Proteins
1761 Brand Concepts
1762 Mangalam Global Enterprise
1763 The Grob Tea Company
1764 Innovative Tyres &amp; Tubes
object of type 'NoneType' has no len()
1765 Airo Lam
1766 The Peria Karamalai Tea &amp; Produce Company
1767 Perfect Infraengineers
Skipping this year for stock 'CAS'
1768 Penta Gold
1769 Accord Synergy
object of type 'NoneType' has no len()
1770 Globe International Carriers
1771 Dhanuka Realty
object of type 'NoneType' has no len()
1772 Jet Knitwears
1773 Innovana Thinklabs
object of type 'NoneType' has no len()
1774 Soni Soya Products
object of type 'NoneType' has no len()
1775 Ahimsa Industries
object of type 'NoneType' has no len()
1776 Mitcon Consultancy &amp; Engineer
1777 Naga Dhunseri Group
1778 Nandani Creation
1779 Jakharia Fabric
1780 Drs Dilip Roadlines
1781 Crown Lifters
1782 Lexus Granito (India)
1783 Latteys Industries
1784 Ascom Leasing &amp; Investments
1785 Euro India Fresh Foods
1786 Servotech Power Systems
1787 Cadsys (India)
object of type 'NoneType' has no len()
1788 Bright Solar
1789 Wonder Electricals
1790 Goldkart Jewels
1791 Focus Lighting &amp; Fixtures
1792 Ushanti Colour Chem
1793 Touchwood Entertainment
1794 Ambani Organics
1795 Continental Seeds &amp; Chemicals
object of type 'NoneType' has no len()
1796 Shree Vasu Logistics
1797 DC Infotech &amp; Communication
1798 Zodiac Energy
1799 Milton Industries
object of type 'NoneType' has no len()
1800 Felix Industries
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'
1801 Parin Furniture
object of type 'NoneType' has no len()
1802 Hindprakash Industries
1803 Madhya Bharat Agro Products
1804 Vera Synthetic
1805 Omfurn India
1806 AVG Logistics
1807 Shree Tirupati Balajee Fibc
1808 Solex Energy
Skipping this year for stock 'CAS'
1809 Madhya Pradesh Today Media
object of type 'NoneType' has no len()
1810 Moksh Ornaments
1811 Bombay Super Hybrid Seeds
1812 ONE POINT ONE
1813 Atal Realtech
1814 Ultra Wiring Connectivity System
1815 Emkay Taps &amp; Cutting Tools
1816 Power &amp; Instrumentation Gujarat
1817 Sikko Industries
1818 Tara Chand Logistic Solutions
1819 Mindpool Technologies
1820 Narmada Agrobase
1821 Kkv Agro Powers
1822 Laxmi Cotspin
1823 Shubhlaxmi Jewel Art
object of type 'NoneType' has no len()
1824 Ani Integrated Services
1825 Silly Monks Entertainment
1826 S.S. Infra Development Consult
object of type 'NoneType' has no len()
1827 Kapston Facilities Management
1828 Pulz Electronics
1829 S K S Textiles
object of type 'NoneType' has no len()
1830 Mohini Health &amp; Hygiene
1831 Secur Credentials
Skipping this year for stock 'CAS'
1832 Univastu India
1833 Jet Freight Logistics
1834 Marvel Decor
1835 Sarveshwar Foods
object of type 'NoneType' has no len()
1836 Aurangabad Distillery
1837 Surani Steel Tubes
object of type 'NoneType' has no len()
1838 Opal Luxury Time Products
1839 United Polyfab Gujarat
1840 We Win
Skipping this year for stock 'CAS'
1841 The Lakshmi Finance &amp; Indust
1842 Transwind Infrastructures
object of type 'NoneType' has no len()
1843 Krishana Phoschem
1844 Vadivarhe Speciality Chem
1845 Vasa Retail &amp; Overseas
1846 Lagnam Spintex
1847 Manav Infra Projects
object of type 'NoneType' has no len()
1848 Jalan Transolutions (India)
Skipping this year for stock 'CAS'
1849 SMVD Poly Pack
object of type 'NoneType' has no len()
1850 AB Infrabuild
object of type 'NoneType' has no len()
1851 CMM Infraprojects
object of type 'NoneType' has no len()
1852 ABM International
object of type 'NoneType' has no len()
1853 The Western India Plywoods
1854 Bohra Industries
Skipping this year for stock 'BAL'
1855 Tirupati Forge
1856 Antarctica
1857 Spacenet Enterprises India
1858 Mask Investments
1859 Bansal Multiflex
object of type 'NoneType' has no len()
1860 Ray Ban Sun Optics India
1861 BDR Buildcon
1862 Supreme India Impex
Skipping this year for stock 'CAS'
Skipping this year for stock 'CAS'

In [153]:



# Function to replace characters in a string


# Replace characters in each string in the list

In [107]:
livemintDetails.head()

,stockLink,stockName
0,https://www.livemint.com/market/market-stats/s...,State Bank Of India
1,https://www.livemint.com/market/market-stats/s...,ICICI Prudential Life Insurance Company
2,https://www.livemint.com/market/market-stats/s...,Reliance Industries
3,https://www.livemint.com/market/market-stats/s...,ICICI Bank
4,https://www.livemint.com/market/market-stats/s...,HDFC Bank

### Get Link and Names of Stocks

In [13]:
!pip install html5lib

Requirement already satisfied: html5lib in c:\users\akshay\anaconda3\envs\tf\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\akshay\anaconda3\envs\tf\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\akshay\anaconda3\envs\tf\lib\site-packages (from html5lib) (0.5.1)

In [32]:
import requests 
from bs4 import BeautifulSoup 
import pandas as pd

liveMintStockDetails = {"stockLink":[],"stockName":[],"stockSymbol":[]}
for i in range(3016,5000):
    try:
        print(f'\rProgress: {i}/{5000}', end='', flush=True)
        URL = "https://www.livemint.com/market/market-stats/stocks-bajaj-finance-share-price-nse-bse-s000{}".format(i) 
        r = requests.get(URL) 
        soup = BeautifulSoup(r.content, 'html5lib')
        stockName_div = str(soup.find('div', attrs = {'class':'stockName'}).find('h1'))
        stockLink_div = str(soup.find('link', attrs = {'rel':'canonical'}))
        sub1 = "<h1>"
        sub2 = "</h1>"
        idx1 = stockName_div.find(sub1)
        idx2 = stockName_div.find(sub2)
        stockName = stockName_div[idx1 + len(sub1): idx2][:-12]
        # print(i,stockName)
        liveMintStockDetails["stockName"].append(stockName)
        sub1 = '<link href="'
        sub2 = 'rel="canonical"/>'
        idx1 = stockLink_div.find(sub1)
        idx2 = stockLink_div.find(sub2)
        stockLink = stockLink_div[idx1 + len(sub1): idx2][:-2]
        liveMintStockDetails["stockLink"].append(stockLink)
        head = soup.head.find_all('script')[0]
        modified_string = str(head).split(":")[-1].split("}")[0].replace('"',"")
        liveMintStockDetails["stockSymbol"].append(modified_string)
    except Exception as e:
        print("Error")
liveMintDf = pd.DataFrame(liveMintStockDetails)
liveMintDf.to_csv("LiveMint.csv")

Progress: 3200/5000Error
Progress: 3273/5000Error
Progress: 3342/5000Error
Progress: 3425/5000Error
Progress: 3498/5000Error
Progress: 3546/5000Error
Progress: 3763/5000Error
Progress: 3764/5000Error
Progress: 3862/5000Error
Progress: 3893/5000Error
Progress: 3956/5000Error
Progress: 3994/5000Error
Progress: 4103/5000Error
Progress: 4127/5000Error
Progress: 4145/5000Error
Progress: 4193/5000Error
Progress: 4213/5000Error
Progress: 4243/5000Error
Progress: 4324/5000Error
Progress: 4351/5000Error
Progress: 4360/5000Error
Progress: 4374/5000Error
Progress: 4382/5000Error
Progress: 4383/5000Error
Progress: 4417/5000Error
Progress: 4422/5000Error
Progress: 4423/5000Error
Progress: 4438/5000Error
Progress: 4444/5000Error
Progress: 4453/5000Error
Progress: 4455/5000Error
Progress: 4468/5000Error
Progress: 4470/5000Error
Progress: 4477/5000Error
Progress: 4491/5000Error
Progress: 4500/5000Error
Progress: 4511/5000Error
Progress: 4516/5000Error
Progress: 4541/5000Error
Progress: 4543/5000Error
Progress: 4546/5000Error
Progress: 4547/5000Error
Progress: 4548/5000Error
Progress: 4557/5000Error
Progress: 4559/5000Error
Progress: 4563/5000Error
Progress: 4564/5000Error
Progress: 4565/5000Error
Progress: 4567/5000Error
Progress: 4582/5000Error
Progress: 4583/5000Error
Progress: 4585/5000Error
Progress: 4599/5000Error
Progress: 4600/5000Error
Progress: 4603/5000Error
Progress: 4604/5000Error
Progress: 4612/5000Error
Progress: 4616/5000Error
Progress: 4626/5000Error
Progress: 4630/5000Error
Progress: 4631/5000Error
Progress: 4633/5000Error
Progress: 4637/5000Error
Progress: 4639/5000Error
Progress: 4641/5000Error
Progress: 4649/5000Error
Progress: 4651/5000Error
Progress: 4653/5000Error
Progress: 4663/5000Error
Progress: 4664/5000Error
Progress: 4665/5000Error
Progress: 4669/5000Error
Progress: 4670/5000Error
Progress: 4671/5000Error
Progress: 4673/5000Error
Progress: 4674/5000Error
Progress: 4675/5000Error
Progress: 4679/5000Error
Progress: 4681/5000Error
Progress: 4684/5000Error
Progress: 4689/5000Error
Progress: 4690/5000Error
Progress: 4693/5000Error
Progress: 4694/5000Error
Progress: 4695/5000Error
Progress: 4696/5000Error
Progress: 4697/5000Error
Progress: 4698/5000Error
Progress: 4708/5000Error
Progress: 4709/5000Error
Progress: 4711/5000Error
Progress: 4715/5000Error
Progress: 4717/5000Error
Progress: 4718/5000Error
Progress: 4724/5000Error
Progress: 4729/5000Error
Progress: 4733/5000Error
Progress: 4734/5000Error
Progress: 4735/5000Error
Progress: 4738/5000Error
Progress: 4743/5000Error
Progress: 4745/5000Error
Progress: 4831/5000Error
Progress: 4893/5000Error
Progress: 4905/5000Error
Progress: 4930/5000Error
Progress: 4954/5000Error
Progress: 4962/5000Error
Progress: 4967/5000Error
Progress: 4971/5000Error
Progress: 4979/5000Error
Progress: 4986/5000Error
Progress: 4987/5000Error
Progress: 4989/5000Error
Progress: 4990/5000Error
Progress: 4991/5000Error
Progress: 4992/5000Error
Progress: 4994/5000Error
Progress: 4995/5000Error
Progress: 4996/5000Error
Progress: 4997/5000Error
Progress: 4998/5000Error
Progress: 4999/5000

In [31]:
liveMintDf

,stockLink,stockName,stockSymbol
0,https://www.livemint.com/market/market-stats/s...,State Bank Of India,SBIN
1,https://www.livemint.com/market/market-stats/s...,ICICI Prudential Life Insurance Company,ICICIPRULI
2,https://www.livemint.com/market/market-stats/s...,Reliance Industries,RELIANCE
3,https://www.livemint.com/market/market-stats/s...,ICICI Bank,ICICIBANK
4,https://www.livemint.com/market/market-stats/s...,HDFC Bank,HDFCBANK
5,https://www.livemint.com/market/market-stats/s...,Yes Bank,YESBANK
6,https://www.livemint.com/market/market-stats/s...,Tata Motors,TATAMOTORS
7,https://www.livemint.com/market/market-stats/s...,Indusind Bank,INDUSINDBK
8,https://www.livemint.com/market/market-stats/s...,Indian Railway Catering &amp; Tourism Corporation,IRCTC
9,https://www.livemint.com/market/market-stats/s...,Larsen &amp; Toubro,LT

In [2]:
import requests 
from bs4 import BeautifulSoup 
import pandas as pd
import json

In [3]:
board_meeting_dict = {'tickerId': [], 'companyName':[] , 'remarks':[] , 'boardMeetDate':[] , 'purpose':[]}
for i in range(3016,5000):
    try:
        print(f'\rProgress: {i}/{5000}', end='', flush=True)
        URL = "https://www.livemint.com/tata-consultancy-services/board-meetings/companyid-s000{}".format(i)
        r = requests.get(URL)
        soup = BeautifulSoup(r.content, 'html5lib')
        script = soup.find('script', attrs = {'id':'__NEXT_DATA__'})  
        line_str = str(script)
        first_line = '<script id="__NEXT_DATA__" type="application/json">'
        second_line = "</script>"
        idx1 = line_str.find(first_line)
        idx2 = line_str.find(second_line)
        result = line_str[idx1 + len(first_line): idx2]
        json_object = json.loads(result)
        json_object = json.loads(result)
        stockFinancialData = json_object['props']['pageProps']
        board_meetings_schedule = stockFinancialData["additionalStockData"]["boardMeetings"]
        for schedule in board_meetings_schedule:
            board_meeting_dict["tickerId"].append(schedule["tickerId"])
            board_meeting_dict["companyName"].append(schedule["companyName"])
            board_meeting_dict["remarks"].append(schedule["remarks"])
            board_meeting_dict["boardMeetDate"].append(schedule["boardMeetDate"])
            board_meeting_dict["purpose"].append(schedule["purpose"])
    except Exception as e:
        print("Error")

Progress: 3200/5000Error
Progress: 3273/5000Error
Progress: 3342/5000Error
Progress: 3425/5000Error
Progress: 3498/5000Error
Progress: 3546/5000Error
Progress: 3763/5000Error
Progress: 3764/5000Error
Progress: 3862/5000Error
Progress: 3893/5000Error
Progress: 3956/5000Error
Progress: 3994/5000Error
Progress: 4103/5000Error
Progress: 4127/5000Error
Progress: 4145/5000Error
Progress: 4193/5000Error
Progress: 4213/5000Error
Progress: 4243/5000Error
Progress: 4324/5000Error
Progress: 4351/5000Error
Progress: 4360/5000Error
Progress: 4374/5000Error
Progress: 4382/5000Error
Progress: 4383/5000Error
Progress: 4417/5000Error
Progress: 4422/5000Error
Progress: 4423/5000Error
Progress: 4438/5000Error
Progress: 4444/5000Error
Progress: 4453/5000Error
Progress: 4455/5000Error
Progress: 4468/5000Error
Progress: 4470/5000Error
Progress: 4477/5000Error
Progress: 4491/5000Error
Progress: 4500/5000Error
Progress: 4511/5000Error
Progress: 4516/5000Error
Progress: 4541/5000Error
Progress: 4543/5000Error
Progress: 4546/5000Error
Progress: 4547/5000Error
Progress: 4548/5000Error
Progress: 4557/5000Error
Progress: 4559/5000Error
Progress: 4563/5000Error
Progress: 4564/5000Error
Progress: 4565/5000Error
Progress: 4567/5000Error
Progress: 4582/5000Error
Progress: 4583/5000Error
Progress: 4585/5000Error
Progress: 4599/5000Error
Progress: 4600/5000Error
Progress: 4603/5000Error
Progress: 4604/5000Error
Progress: 4612/5000Error
Progress: 4616/5000Error
Progress: 4626/5000Error
Progress: 4630/5000Error
Progress: 4631/5000Error
Progress: 4633/5000Error
Progress: 4637/5000Error
Progress: 4639/5000Error
Progress: 4641/5000Error
Progress: 4649/5000Error
Progress: 4651/5000Error
Progress: 4653/5000Error
Progress: 4663/5000Error
Progress: 4664/5000Error
Progress: 4665/5000Error
Progress: 4669/5000Error
Progress: 4670/5000Error
Progress: 4671/5000Error
Progress: 4673/5000Error
Progress: 4674/5000Error
Progress: 4675/5000Error
Progress: 4679/5000Error
Progress: 4681/5000Error
Progress: 4684/5000Error
Progress: 4689/5000Error
Progress: 4690/5000Error
Progress: 4693/5000Error
Progress: 4694/5000Error
Progress: 4695/5000Error
Progress: 4696/5000Error
Progress: 4697/5000Error
Progress: 4698/5000Error
Progress: 4708/5000Error
Progress: 4709/5000Error
Progress: 4711/5000Error
Progress: 4715/5000Error
Progress: 4717/5000Error
Progress: 4718/5000Error
Progress: 4724/5000Error
Progress: 4729/5000Error
Progress: 4733/5000Error
Progress: 4734/5000Error
Progress: 4735/5000Error
Progress: 4738/5000Error
Progress: 4743/5000Error
Progress: 4745/5000Error
Progress: 4831/5000Error
Progress: 4893/5000Error
Progress: 4905/5000Error
Progress: 4930/5000Error
Progress: 4954/5000Error
Progress: 4962/5000Error
Progress: 4967/5000Error
Progress: 4971/5000Error
Progress: 4979/5000Error
Progress: 4986/5000Error
Progress: 4987/5000Error
Progress: 4989/5000Error
Progress: 4990/5000Error
Progress: 4991/5000Error
Progress: 4992/5000Error
Progress: 4994/5000Error
Progress: 4995/5000Error
Progress: 4996/5000Error
Progress: 4997/5000Error
Progress: 4998/5000Error
Progress: 4999/5000

In [49]:
board_meeting_dict

{'tickerId': ['S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003016',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003017',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003018',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003019',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003020',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003021',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003022',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003023',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003024',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025',
  'S0003025'],
 'companyName': ['State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'State Bank Of India',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'ICICI Prudential Life Insurance Company',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'Reliance Industries',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'ICICI Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'HDFC Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Yes Bank',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Tata Motors',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indusind Bank',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Indian Railway Catering & Tourism Corporation',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro',
  'Larsen & Toubro'],
 'remarks': ['Inter alia, to seek approval for raising of Long-Term Bonds through a public issue or private placement of suitable tenor in compliance with SEBI guidelines, during the financial year 2024-25.',
  '',
  '',
  '',
  '',
  '',
  'To consider Fund Raising',
  '',
  'Inter alia, to consider and approve Prior intimation for meeting of the Executive Committee of the Central Board to seek approval for raising of Infrastructure Bonds.',
  'Inter alia, To seek approval for raising of Infrastructure Bonds up to an amount of Rs. 10,000 crores (including a green shoe option of Rs. 5,000 crores) through a public issue or private placement.',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Inter alia, to consider and approve To seek approval for raising of Additional Tier 1 (AT 1) Capital by way of issuance of Basel III compliant debt instrument in USD and / or INR through a Public offe',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Inter alia, may consider annual renewal of issuance of Long-Term Bonds (Financing of Infrastructure & Affordable Housing), Perpetual Debt Instruments (part of Additional Tier I & Tier II capital bonds',
  '',
  '',
  '',
  'Inter alia, proposes to raise funds by issuing Perpetual Debt Instruments (part of Additional Tier I capital), Tier II Capital Bonds and Long-Term Bonds up to total amount of Rs. 50,000 crores.',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Inter alia, to consider and approve by the Capital Raising Committee the exercise of certain rights available to the Bank under the terms and conditions of the Medium Term Note programme.',
  '',
  'To take on record voting results for early redemption of Bonds and to consider and approve Redemption/Interest payment date and further actions.',
  'Intimation of the date of the Capital Raising Committee Meeting for considering proposal for seeking investor approval for early redemption of Basel II Tier 2 bonds.',
  '',
  '',
  '',
  '',
  '',
  'Inter alia, to consider and approve To consider Fund Raising',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'The Board in the said Meeting would also consider a proposal for raising funds by way of issue of one or more instruments.',
  '',
  '',
  '',
  '',
  'To consider Fund Raising through debt securities in any permitted mode on a private placement basis.',
  '',
  '',
  '',
  '',
  '',
  "Inter alia, to consider : 1. Fix the date and time for the 28th Annual General Meeting (' ;\\GM') of the Bank and other related matters.",
  '',
  '',
  '',
  'To consider Fund Raising',
  '',
  'inter-alia, to consider the proposal of raising funds through debt securities or equity instruments or convertible debt securities in any permitted mode. (Revised)',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Inter alia, to consider fund raising including by way of debt issue',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  "inter-alia to seek approval for raising funds including through issue of debt securities as part of Company's refinancing program.",
  '',
  '',
  '',
  '',
  ''],
 'boardMeetDate': ['2024-06-19',
  '2024-05-09',
  '2024-02-03',
  '2023-11-04',
  '2023-08-04',
  '2023-05-18',
  '2023-04-18',
  '2023-02-03',
  '2023-01-03',
  '2022-11-29',
  '2022-11-05',
  '2022-08-06',
  '2022-07-20',
  '2022-05-13',
  '2022-05-10',
  '2022-02-05',
  '2021-11-03',
  '2021-08-04',
  '2021-06-21',
  '2021-05-21',
  '2021-02-04',
  '2024-07-23',
  '2024-04-23',
  '2024-01-17',
  '2023-10-17',
  '2023-07-18',
  '2023-04-20',
  '2023-01-17',
  '2022-10-15',
  '2022-07-16',
  '2022-04-16',
  '2022-01-18',
  '2021-10-19',
  '2021-07-20',
  '2021-04-19',
  '2021-01-27',
  '2024-04-22',
  '2024-01-19',
  '2023-10-27',
  '2023-07-21',
  '2023-04-21',
  '2023-01-20',
  '2022-10-21',
  '2022-07-22',
  '2022-05-06',
  '2022-01-21',
  '2021-10-22',
  '2021-07-23',
  '2021-04-30',
  '2021-01-22',
  '2024-07-27',
  '2024-04-27',
  '2024-01-20',
  '2023-10-21',
  '2023-07-22',
  '2023-04-22',
  '2023-01-21',
  '2022-10-22',
  '2022-07-23',
  '2022-04-23',
  '2022-01-22',
  '2021-10-23',
  '2021-07-24',
  '2021-04-24',
  '2021-01-30',
  '2024-04-20',
  '2024-01-16',
  '2023-10-15',
  '2023-07-17',
  '2023-04-15',
  '2023-01-14',
  '2022-10-15',
  '2022-07-16',
  '2022-04-23',
  '2022-04-16',
  '2022-01-15',
  '2021-10-16',
  '2021-07-17',
  '2021-06-18',
  '2021-04-17',
  '2021-01-16',
  '2024-07-20',
  '2024-04-27',
  '2024-01-27',
  '2023-10-21',
  '2023-07-22',
  '2023-04-22',
  '2023-01-21',
  '2022-10-22',
  '2022-07-29',
  '2022-07-23',
  '2022-06-02',
  '2022-04-30',
  '2022-04-12',
  '2022-02-11',
  '2022-01-22',
  '2021-10-22',
  '2021-07-23',
  '2021-06-10',
  '2021-04-30',
  '2021-01-22',
  '2024-05-10',
  '2024-02-02',
  '2023-11-02',
  '2023-07-25',
  '2023-05-12',
  '2023-01-25',
  '2022-11-09',
  '2022-07-27',
  '2022-05-12',
  '2022-01-31',
  '2021-11-01',
  '2021-07-26',
  '2021-05-18',
  '2021-01-29',
  '2024-04-25',
  '2024-01-18',
  '2023-10-18',
  '2023-07-20',
  '2023-07-18',
  '2023-04-24',
  '2023-01-18',
  '2022-10-19',
  '2022-07-20',
  '2022-07-18',
  '2022-04-29',
  '2022-01-29',
  '2021-10-27',
  '2021-10-21',
  '2021-07-27',
  '2021-07-24',
  '2021-07-23',
  '2021-04-30',
  '2021-01-29',
  '2024-05-28',
  '2024-02-13',
  '2023-11-07',
  '2023-08-09',
  '2023-05-29',
  '2023-02-09',
  '2022-11-14',
  '2022-08-10',
  '2022-05-30',
  '2022-02-08',
  '2021-11-01',
  '2021-08-12',
  '2021-06-29',
  '2021-01-28',
  '2024-05-08',
  '2024-03-27',
  '2024-01-30',
  '2023-10-31',
  '2023-07-25',
  '2023-05-10',
  '2023-01-30',
  '2022-10-31',
  '2022-07-26',
  '2022-05-12',
  '2022-03-24',
  '2022-01-28',
  '2021-10-27',
  '2021-07-26',
  '2021-05-14',
  '2021-01-25'],
 'purpose': ['Others',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Dividend',
  'Others',
  'Quarterly Results',
  'Others',
  'Others',
  'Quarterly Results',
  'Quarterly Results',
  'To consider raising of funds',
  'Audited Results & Dividend',
  'Others',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Others',
  'Audited Results & Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results',
  'Audited Results',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results & Final Dividend',
  'Audited Results',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Audited Results, Final Dividend & Others',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results, Final Dividend & Others',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Final Dividend',
  'Audited Results',
  'Quarterly Results',
  'Audited Results',
  'Quarterly Results',
  'Dividend',
  'Audited & Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results',
  'Quarterly Results',
  'Quarterly Results',
  'Others',
  'Quarterly Results',
  'Others',
  'Audited Results',
  'Others',
  'Others',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'To consider raising of funds',
  'Audited Results',
  'Quarterly Results & Others',
  'Audited Results & Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited & Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Others',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Others',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Others',
  'Audited Results & Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Others',
  'Quarterly Results',
  'Others',
  'Others',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Quarterly Results & Interim Dividend',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results & Interim Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Quarterly Results & Interim Dividend',
  'Quarterly Results',
  'Quarterly Results & Stock Split',
  'Audited Results & Final Dividend',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Others',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Dividend',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Final Dividend',
  'Others',
  'Quarterly Results',
  'Quarterly Results',
  'Quarterly Results',
  'Audited Results & Dividend',
  'Quarterly Results']}

In [5]:
pd.DataFrame(board_meeting_dict).to_csv("diclosure_dates_2.csv")